# Goal -> Automate the linting of python code
# Description: Whenever changes made in any .py file/s then the python Linter will automatically checks -syntax, format and indentation.

name: Auto Linter

on:
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
    #Step 1 - cloning the code of current branch into the runner
      - name: Checkout/Clone the code
        uses: actions/checkout@v7

    #Step 2 - install python
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

    #Step 3 - install the Linting tool for python
      - name: Install Linter
        run: pip install ruff

    #Step 4 - Running Linter to check syntax, indenatation , format 
      - name: Run Linter
        run: ruff check . 
      
    

    
